### ISSUE TITLE
Вопросы по git/github, которые нужно рассказать в докладе

### ISSUE THREAD

**Issue by alexbaumgertner** [easy-deep-learning/git-effective-workflow#1]
- [ ] Настройка git (username, useremail)
- [ ] Как и зачем делать коммит (кратко: это не кнопка `save`, а атомарная операция like "прикрутил болт, припаял клемму, поменял лампочку")
- [ ] Название коммитов и pull request
- [ ] Как назначить ревьювера (или почистите наконец почтовый ящик и отпишитесь от ненужных рассылок)
- [ ] Как делать ревью кода: полезные замечания, кнопка `Start a review` (отправить замечания одним разом, а не 100500 отдельных замечаний)
- [ ] Как мерджить пулл-реквесты:  merge/squash_and_merge/rebase_and_merge — разница и особенности, удалять старые ветки
- [ ] Управление историей коммитов: `rebase -i` и `git reflog` (что это под капотом)
- [ ] Как найти багу: `git bisect`
- [ ] Выпуск релизов, `git tag`
- [ ] Как устроен гит(что такое HEAD, бранч, коммит, репозиторий, индекс и т.д.) и как это все работает ([think like a git](http://think-like-a-git.net/))
- [ ] Как найти что-то в логе гита? Полезные фичи, о которых мы забываем
- [ ] git blame
- [ ] специфика работы с локальным репозиторием и несколькими remote (`git fetch --all`, `git rebase upstream/master` и тд)
-  [ ] submodule git и почему их не стоит использовать)
-  [ ] Методологии работы с репозиторием в команде: git flow, github flow, gitlab flow, какой-нибудь [фичебранч](https://hackernoon.com/still-using-gitflow-what-about-a-simpler-alternative-74aa9a46b9a3)
- [ ] git stash
- [ ] зачем нужна пустая линия в конце файла (спойлер: чтобы не было merge-конфликтов)
- [ ] Рассказать о Инструменты-Git-Интерактивное-индексирование
- [ ] приемы работы с сайтом Github

```
// Удалить все локальные ветки, кроме master
git branch | grep -v 'master' | xargs git branch -D
```

**Comment by amalinko** [comment]
Крутая идея! Я бы не уделял внимания таким вопросам, как настройка имени и как назначить ревьюера, т.е. таким, в которых самому разобраться очень просто.
Последние четыре вопроса очень интересные.
От себя вопросы:
1. Как устроен гит(что такое HEAD, бранч, коммит, репозиторий, индекс и т.д.) и как это все работает
2. Как найти что-то в логе гита? Полезные фичи, о которых мы забываем
3. git blame

**Comment by alexbaumgertner** [comment]
@artemMalinko спасибо, добавил!

**Comment by fizzka** [comment]
(git) я бы отразил специфику работы с локальным репозиторием и несколькими remote

**Comment by klerick** [comment]
submodule git и почему их не стоит использовать)

**Comment by alexbaumgertner** [comment]
@klerick огонь, спасибо, добавил!

**Comment by stcherenkov** [comment]
Методологии работы с репозиторием в команде: git flow, github flow, gitlab flow, какой-нибудь [фичебранч](https://hackernoon.com/still-using-gitflow-what-about-a-simpler-alternative-74aa9a46b9a3).

Работа с метками.

**Comment by sergey-platonov** [comment]
Мне кажется или в докладе ни слова о воркфлоу?

**Comment by eduard-sukharev** [comment]
Я бы хотел узнать про reflog и иже с ним. Это для меня какая-то тёмная вещь, типа истории действий в гите. Не просто как откатить гит стэш поп/апплай, а именно что это такое и как оно работает.

**Comment by alexbaumgertner** [comment]
Рассказать о [Инструменты-Git-Интерактивное-индексирование](https://git-scm.com/book/ru/v1/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-Git-%D0%98%D0%BD%D1%82%D0%B5%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D0%B5-%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)

**Comment by sergey-platonov** [comment]
git rebase vs git merge
